### ISSUE TITLE
How to find the optimal beam index of each data point?

### ISSUE THREAD

**Issue by irfanfadhullah** [LacoLuo/S2S-BT#1]
Hello, I want to ask you how to find the optimal beam index of each data point? 
Can you provide or share the code? Thank you

**Comment by LacoLuo** [comment]
Hi, I have uploaded the preprocessing codes and written their usage in README. Hope these updates would be helpful to you.

**Comment by irfanfadhullah** [comment]
HI,I appreciate that you giving me the information I need to preprocess the dataset.. Thank you.
